# Generated by Django 2.2.6 on 2019-10-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('foto', models.ImageField(blank=True, upload_to='image_perfil')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=10, unique=True)),
                ('telefone', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=12)),
                ('foto', models.ImageField(blank=True, upload_to='image_perfil')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appwnl.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=50)),
                ('desenvolvedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appwnl.Desenvolvedor')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appwnl.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('aprovado', models.BooleanField(null=True)),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appwnl.Desenvolvedor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appwnl.Empresa')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appwnl.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=20)),
                ('desenvolvedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appwnl.Desenvolvedor')),
            ],
        ),
    ]
